version: '3.9'

services:
  db:
    image: postgres:16
    container_name: tilit_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tilit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salasana
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  web:
    build: .
    container_name: tilit_web
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tilit.rule=Host(`tilit.drafter.lol`)"
      - "traefik.http.routers.tilit.entrypoints=websecure"
      - "traefik.http.routers.tilit.tls.certresolver=myresolver"
      - "traefik.http.services.tilit.loadbalancer.server.port=80"

volumes:
  db_data:

networks:
  traefik_proxy:
    external: true


